#!/bin/sh
# SPDX-License-Identifier: GPL-2.0

usage() {
	echo "Usage: $0 [--save-scmversion] [srctree] [branch] [kmi-generation]" >&2
	exit 1
}

scm_only=false
srctree=.

if test "$1" = "--save-scmversion"; then
	scm_only=true
	shift
fi

if test $# -gt 0; then
	srctree=$1
	shift
fi

while test $# -gt 0; do
	shift
done

if test ! -d "$srctree"; then
	usage
fi

if $scm_only; then
	exit 0
fi

if test -e include/config/auto.conf; then
	. include/config/auto.conf
else
	echo "Error: kernelrelease not valid - run 'make prepare' to update it" >&2
	exit 1
fi

echo "-〩Beler"
